// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbmoncbkwuegugkjftyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ibW9uY2Jrd3VlZ3Vna2pmdHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODU1NjksImV4cCI6MjA2NjE2MTU2OX0.9G2DUtSU8ysMnqg64Rrn20YXGF23ABTgZQGiZDIQDFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);